#!/bin/sh
# Copyright (c) 2022-2023, AllWorldIT.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# shellcheck disable=SC2164
cd /opt/mastodon

# Load Mastodon configuration
set -a
# shellcheck disable=SC1091
. mastodon.env
set +a

# Load our MASTODON_MODE env
# shellcheck disable=SC1091
. .mode.env


if [ "$MASTODON_MODE" = "web" ]; then
	_bundle=$(which bundle)
	exec "$_bundle" exec rails server -p 3000 -b "$BIND"

elif [ "$MASTODON_MODE" = "streaming" ]; then
	_node=$(which node)
	exec "$_node" ./streaming/index.js

elif [ "$MASTODON_MODE" = "sidekiq" ]; then
	_bundle=$(which bundle)
	exec "$_bundle" exec sidekiq
fi
